### ISSUE TITLE
control camera servos

### ISSUE THREAD

**Issue by isaiahkahler** [FRC5263/2018Robot#19]
2 continuous servos are attached to the camera, implementation of controls needed.

**Comment by elodotwe** [comment]
Continuous servos? As in, ones that continue rotating as long as power is
applied? How do you plan to control that?

**Comment by isaiahkahler** [comment]
Yes continuous servos. I asked some builders to think about a design and they handed me the camera setup we now have attached on top of programmers' bot. I was thinking we could use the D-pad or something to control the camera's direction. Weirdly enough, the servos attached are not the same kind. There is a continuous rotation for the X axis (HSR-1425CR), and a 180 servo for the Y axis (HS-485HB). How it's now set up, we can replace the continuous rotation servo without too much hassle. The servo heads may also need some re-calibration, so we can do that too. In the screensteps website there is an example for positional servos, but not continuous, so we might be forced to switch it out.

**Comment by isaiahkahler** [comment]
Update: 

- Switched out CR servo for 180 servo

- Added Servo objects in Vision subsystem

- Created Camera control with D-pad in driver control command
