### ISSUE TITLE
What do we want the robot to do?

### ISSUE THREAD

**Issue by elodotwe** [FRC5263/2018Robot#2]
Let's document our assumptions here.

Rough idea, what should we be doing in autonomous? Ideas? Guesses?

I'll start. We'll surely want to be able to cross the AUTO LINE in autonomous. What else?

**Comment by barnes12** [comment]
If vision is working, loading cubes on the switch shouldn't be a problem,
it doesn't seem to be that hard of a target even without vision.

**Comment by EvanGeiss** [comment]
We can definitely put a block on the switch. Vision will work.

**Comment by elodotwe** [comment]
Do we need vision? I mean...
https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details

Just playing devil's advocate :)

>
