### ISSUE TITLE
Switching Between Test bot and Competition bot

### ISSUE THREAD

**Issue by isaiahkahler** [FRC5263/2018Robot#23]
I have an idea that might make it a lot easier to switch between test robot and competition bot. 
Obviously, the two bots will not be identical, and next years, and the year after that, will also be unique in some way. The wheel diameter may change, the offset location of the ultrasonic, the number of encoder clicks on the gear box; they are all subject to change. What if we had one variable to change between builds, that then affected all the other variables? Imagine this:
### In Robot.java
``` java
String botType = "test bot"; //change to "comp bot" when using competition robot
```
### In any command or subsystem:
``` java
if(Robot.botType.equals("test bot")){
    double encoderClicksPerRevolution = 360;
} else {
   double encoderClicksPerRevolution = 1440;
}
```

**Comment by elodotwe** [comment]
This is completed, I think-- @isaiahkahler if you disagree feel free to reopen.
