### ISSUE TITLE
CommandGroup Package

### ISSUE THREAD

**Issue by EvanGeiss** [FRC5263/2018Robot#24]
Currently, our project has three folders, **robot**, **commands** and **subsystems**. I think we should make a fourth, strictly for **command groups**. In this package, we would create all of our command groups. Instead of having a bunch of commands and command groups together in one package.

**Comment by elodotwe** [comment]
Do we still want to follow through on this?

**Comment by EvanGeiss** [comment]
I really think it's a good idea. We just need to decide.
