### ISSUE TITLE
Arm Subsystem

### ISSUE THREAD

**Issue by isaiahkahler** [FRC5263/2018Robot#27]
### To Do:

- Create Arm Subsystem

- Create motor controller object and respective methods

- Create Arm moving command(s) to call when a button is pressed for driver control OR directly control arm movement in driver control

**Comment by elodotwe** [comment]
I think we have an arm subsystem now. I'm going to close this. But we have some issues with how the arm subsystem is laid out; I'll create separate issue(s) for that.
