### ISSUE TITLE
List of Ports

### ISSUE THREAD

**Issue by EvanGeiss** [FRC5263/2018Robot#29]
Camera Servos- PWM3
Left Motor Controllers- PWM0
Camera Mount Servos- PWM2
Right Motor Controllers- PWM1
Left Drive Motor- DIO0/1
Right Drive Motor- DIO2/3
UltraSonic Output- DIO4
UltraSonic Input- Dio5

**Comment by elodotwe** [comment]
I think it's okay to refer to RobotMap.java for the channel mappings. I think we've finally migrated every channel assignment to that file.
