### ISSUE TITLE
Rotation PID Location?

### ISSUE THREAD

**Issue by isaiahkahler** [FRC5263/2018Robot#30]
Right now f dsjlaf jdskal jfldkajl ILL UP DATE THIS LATER

**Comment by elodotwe** [comment]
@isaiahkahler do you remember what this was about? Is this still relevant?

**Comment by isaiahkahler** [comment]
The question was if we should move the `PIDController` for rotation into a its own command, or leave it inside the `DriveTrain` subsystem and call its methods from a command. We went with the second option.
