### ISSUE TITLE
Change joystick naming convention

### ISSUE THREAD

**Issue by elodotwe** [FRC5263/2018Robot#32]
https://github.com/FRC5263/2018Robot/blob/c8088d6830c838b4b707410d913f97492e243a82/src/org/usfirst/frc/team5263/robot/OI.java#L69-L75

Can we update these to use more obvious names? Maybe `driveTrainJoystick` and `armJoystick` or `pilot` and `copilot` or something which clearly differentiates between the two sticks without us having to think about it.

The sticks and the `getButton` functions should use the same naming convention, i.e. the Joystick definitions like `public Joystick main = new Joystick(0);` should change from `main` to whatever we decide, and `getButton` should become `getWhateverWeDecideButton()`.

**Comment by EvanGeiss** [comment]
Just did this. Closing.
