### ISSUE TITLE
Remove unused Buttons from OI

### ISSUE THREAD

**Issue by elodotwe** [FRC5263/2018Robot#33]
https://github.com/FRC5263/2018Robot/blob/c8088d6830c838b4b707410d913f97492e243a82/src/org/usfirst/frc/team5263/robot/OI.java#L48-L51

https://github.com/FRC5263/2018Robot/blob/c8088d6830c838b4b707410d913f97492e243a82/src/org/usfirst/frc/team5263/robot/OI.java#L54-L57

Looks like we're not using these Button declarations? Can they be removed?

**Comment by EvanGeiss** [comment]
Just did this. Closing.
